apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: court-of-honor
  namespace: default
spec:
  template:
     spec:
       containers:
         - name: site
           image:  gcr.io/rjjr-2020/rjjr-website
           imagePullPolicy: Always
           ports:
             - containerPort: 80
