apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-troop
  namespace: default
spec:
  template:
     spec:
       containers:
         - name: compiler
           image:  gcr.io/rjjr-2020/make-rust
           imagePullPolicy: Always
           ports:
             - containerPort: 8011
           readinessProbe:
             httpGet:
               path: /ping
             timeoutSeconds: 3 
             periodSeconds: 10
             failureThreshold: 3
           livenessProbe:
             httpGet:
               path: /ping
             timeoutSeconds: 3
             periodSeconds: 10
             failureThreshold: 3
