apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-deployment
  labels:
    app: {{.Chart.Name}}-deployment
spec:
   replicas: 3
   selector:
     matchLabels:
       app: {{.Chart.Name}}-deployment
   template:
     metadata:
       labels:
         app: {{.Chart.Name}}-deployment
     spec:
       containers:
         - name: compiler
           image:  gcr.io/rjjr-2020/make-rust
           imagePullPolicy: Always
           ports:
             - containerPort: 8011
           readinessProbe:
             httpGet:
               path: /list
               port: 8011
             timeoutSeconds: 15
             timeoutSeconds: 15
             periodSeconds: 60
           livenessProbe:
             httpGet:
               path: /list
               port: 8011
             timeoutSeconds: 15
             periodSeconds: 60

