name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
         GCP_TOKEN: ${{secrets.GCP_TOKEN}}
      run: cd backend && echo $GCP_TOKEN > key.json && docker build . --file Dockerfile --tag gen-wasm:$(date +%s)
